const constants = {
  dropdown: {
    ALLRELATIONSHIP: "ALLRELATIONSHIP",
    ALLREFERENCE: "ALLREFERENCE",
    ALLREFEREDTYPE: "ALLREFEREDTYPE",
    ALLCOUNTRY: "ALLCOUNTRY",
    ALLCENTER: "ALLCENTER",
    ALLGROUPACTIVITY:"ALLGROUPACTIVITY",
    ALLROLES: "ALLROLES",
    ALLSUBSESSION: "ALLSUBSESSION"
  }
};

export default constants;
